apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-permissions
  namespace: microblog-app
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-permissions-binding
  namespace: microblog-app
subjects:
  - kind: ServiceAccount
    name: default
    namespace: microblog-app
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: default-permissions
  apiGroup: ""