server:
  port: 80

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: match-service
          uri: http://match-service:80
          predicates:
            - Path= /api/venues*, /api/venues/**,        >
                    /api/referees*, /api/referees/**,    >
                    /api/coaches*, /api/coaches/**,      >
                    /api/countries*, /api/countries/**   >
                    /api/players*, /api/players/**

management:
  endpoint:
    health:
      probes:
        enabled: true
