server:
  port: 80

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: match-service
          uri: http://match-service:80
          predicates:
            - Path= /api/venues*, /api/venues/**,
                    /api/referees*, /api/referees/**,
                    /api/coaches*, /api/coaches/**,
                    /api/countries*, /api/countries/**,
                    /api/players*, /api/players/**,
                    /api/teams*, /api/teams/**,
                    /api/matches*, /api/matches/**,
        - id: match-service-socket-io
          uri: http://match-service:81
          predicates:
            - Path= /socket.io*, /socket.io/**, # socket.io handshake route
                    /api/ws/match-events*, /api/ws/match-events/** # namespace for subscribing to match events

management:
  endpoint:
    health:
      probes:
        enabled: true
