apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: sports-live-app
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: echelon133/gateway-service:0.1.0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /actuator/health/readiness
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 80
              path: /actuator/health/liveness
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: sports-live-app
  labels:
    app: gateway-service
    spring-boot: "true"
spec:
  ports:
    - protocol: "TCP"
      port: 80
  selector:
    app: gateway-service
  type: LoadBalancer