server:
  port: 80

socket-io:
  host: "0.0.0.0"
  port: 81

spring:
  kafka:
    bootstrap-servers: http://kafka-service:9092
  application:
    name: match-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://match-service-postgres:5432/${SECRET_POSTGRES_DB}
    username: ${SECRET_POSTGRES_USERNAME}
    password: ${SECRET_POSTGRES_PASSWORD}


management:
  endpoint:
    health:
      probes:
        enabled: true