server:
  port: 80

feign:
  autoconfiguration:
    jackson:
      enabled: true

spring:
  kafka:
    bootstrap-servers: http://kafka-service:9092
  application:
    name: competition-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://competition-service-postgres:5432/${SECRET_POSTGRES_DB}
    username: ${SECRET_POSTGRES_USERNAME}
    password: ${SECRET_POSTGRES_PASSWORD}

management:
  endpoint:
    health:
      probes:
        enabled: true
